services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: CryptoBalance

  init:
    image: mathieumafille/cryptobalance-init:latest

  frontend:
    image: mathieumafille/cryptobalance-frontend:latest
    restart: always
    ports:
      - 5000:5000

  backend:
    image: mathieumafille/cryptobalance-backend:latest
    restart: always

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080